spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=GEEdjrTkLLOUiWiRaPqsWkRXdyyIMweS



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.root=WARN

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized